In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [2]:
reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [3]:
one_hot("amazing restaurant",30)

[21, 19]

In [4]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
encoded_reviews

[[24, 16],
 [21, 19],
 [4, 28],
 [12, 20, 8],
 [5, 28, 9],
 [20, 16],
 [7, 28, 5],
 [13, 17],
 [13, 19],
 [19, 26]]

In [5]:
max_length = 3
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
padded_reviews

array([[24, 16,  0],
       [21, 19,  0],
       [ 4, 28,  0],
       [12, 20,  8],
       [ 5, 28,  9],
       [20, 16,  0],
       [ 7, 28,  5],
       [13, 17,  0],
       [13, 19,  0],
       [19, 26,  0]])

In [6]:
embeded_vector_size = 5

model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length, name='embedding'))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [7]:
X = padded_reviews
y = sentiment

In [8]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 3, 5)              150       
                                                                 
 flatten (Flatten)           (None, 15)                0         
                                                                 
 dense (Dense)               (None, 1)                 16        
                                                                 
Total params: 166
Trainable params: 166
Non-trainable params: 0
_________________________________________________________________


In [9]:
model.fit(X, y, epochs=20, verbose=0)

In [10]:
model.evaluate(X, y)

1/1 [==============================] - 0s 402ms/step - loss: 0.6728 - accuracy: 0.9000


[0.6728149652481079, 0.8999999761581421]

In [11]:
weights = model.get_layer('embedding').get_weights()[0]
weights

array([[-0.04134525,  0.02397438,  0.04764894, -0.01768957, -0.02007526],
       [ 0.03474179, -0.01286986,  0.01048927,  0.024664  ,  0.00032846],
       [ 0.01903022, -0.0120513 ,  0.0337153 ,  0.01806339, -0.02970247],
       [-0.04824036, -0.04080521,  0.01281439,  0.04491695,  0.02381425],
       [-0.00425882, -0.03540402,  0.04716816,  0.05954983,  0.0017135 ],
       [-0.00616793,  0.00204764,  0.03315692,  0.01652372,  0.03644911],
       [-0.01742782, -0.03949033, -0.04885245,  0.04297299,  0.00081063],
       [ 0.00975202,  0.04908594, -0.03492306,  0.01439613, -0.04987923],
       [ 0.05524975,  0.04143382, -0.06078777,  0.02098113, -0.00375032],
       [-0.01234272,  0.01517439,  0.0051191 ,  0.04652904, -0.02065785],
       [ 0.02780277, -0.00829268, -0.01873185,  0.02862332, -0.0337975 ],
       [ 0.0399448 , -0.03931322,  0.04196617,  0.03319503,  0.00040384],
       [ 0.04158963, -0.01318916, -0.01978435,  0.03255972,  0.01815832],
       [-0.01621051,  0.00248238, -0.0

In [12]:
len(weights)

30

In [13]:
weights[13]

array([-0.01621051,  0.00248238, -0.03290231, -0.02631269,  0.02505406],
      dtype=float32)

In [14]:
weights[8]

array([ 0.05524975,  0.04143382, -0.06078777,  0.02098113, -0.00375032],
      dtype=float32)