In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits = load_digits()

In [2]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)

In [3]:
lr = LogisticRegression(max_iter=200)
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9611111111111111

In [4]:
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.9796296296296296

In [5]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9574074074074074

### KFold cross validation

In [6]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [7]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


#### Use KFold for digits example

In [8]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [9]:
get_score(SVC(), X_train, X_test, y_train, y_test)

0.9796296296296296

In [10]:
from sklearn.model_selection import StratifiedKFold
sff = StratifiedKFold(n_splits=3)

scores_lr = []
scores_svm = []
scores_rf = []

for train_index, test_index in kf.split(digits.data):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]
    scores_lr.append(get_score(LogisticRegression(max_iter=200), X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test))

In [11]:
scores_lr

[0.9248747913188647, 0.9432387312186978, 0.9148580968280468]

In [12]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [13]:
scores_rf

[0.9382303839732888, 0.9565943238731218, 0.9232053422370617]

### cross_val_score function

In [14]:
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(max_iter=200), digits.data, digits.target)

array([0.92222222, 0.87222222, 0.94428969, 0.94150418, 0.89693593])

In [15]:
cross_val_score(SVC(), digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [16]:
cross_val_score(RandomForestClassifier(), digits.data, digits.target)

array([0.92222222, 0.90555556, 0.95821727, 0.97493036, 0.9275766 ])